---
title: "USBondAnalysis"
author: "Shubham Misar"
date: "2023-06-17"
output: html_document
---

```{r}
library(tsibble)
library(dplyr)
library(ggplot2)
library(fabletools)
library(feasts)
library(tsibbledata)

```

```{r}
df <- read.csv("FED-SVENY.csv")
```

```{r}
head(df)
```

Lets Convert the Date column into datetime format and make it into index

```{r}
df<-df %>% 
  mutate(Date = as.Date(Date)) %>% 
  as_tsibble(index = Date)
```

```{r}
head(df)
```

```{r}
df %>% 
  autoplot(SVENY01) +
  labs(
    x = "Date",
    y = "1 Year Bond",
    title = "1 Year Bond Returns"
  )
```

```{r}
df_long <- df %>%
  pivot_longer(cols = -Date, names_to = "Variable", values_to = "Value")
```

```{r, warning=FALSE}
library(ggplot2)
library(ggthemes)

df_long %>%
  ggplot(aes(x = Date, y = Value, color = Variable)) +
  geom_line(linetype = "solid", size = 1.5) +  
  scale_color_viridis_d() +  
  labs(
    x = "Date",
    y = "Bond Yield in %",
    title = "Bond Yield Comparison"
  ) +
  theme_minimal() +  
  theme(
    plot.title = element_text(size = 16, face = "bold"),  
    axis.title = element_text(size = 14),  
    axis.text = element_text(size = 12),  
    legend.title = element_blank(),  
    legend.position = "bottom"  
  )

```

As the term for investment increases the returns are higher. </br> During the 1980s The investment percentage was the highest. </br>

```{r}

```
